language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt"
script:
    - tox
    - nosetests -v --with-coverage --cover-package=dapi --exe
notifications:
    email:
        recipients:
            - leannmak@139.com
        on_success: always
        on_failure: always

branches:
    only:
        - master

after_success:
    - coveralls
